package rs.example.carbon_traders.carboncredit.entity;

import java.time.LocalDateTime;

import jakarta.persistence.*;
import lombok.*;

import rs.example.carbon_traders.farmer.entity.Farmer;
import rs.example.carbon_traders.company.entity.Company;

@Entity
@Table(name = "carbon_credits")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CarbonCredit {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // cradit generated by farmer
    @Column(nullable = false)
    private Double totalCredits;

    // cradit avaliable for sale
    @Column(nullable = false)
    private Double availableCredits;

    //sold cradit
    private Double soldCredits = 0.0;

    // Price of single cradit
    @Column(nullable = false)
    private Double pricePerCredit;

    // CREDIT STATUS
    // GENERATED, PARTIALLY_SOLD, SOLD
    private String status;

    // Farmer who owns this credit
    @ManyToOne
    @JoinColumn(name = "farmer_id", nullable = false)
    private Farmer farmer;

    // Company who bought credits (nullable until sold)
    @ManyToOne
    @JoinColumn(name = "company_id")
    private Company company;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}

